### ISSUE TITLE
No video on Alienware QD-OLED monitor since November update, EDID conformity failure

### ISSUE THREAD

**Issue by ameturpoet** [ValveSoftware/gamescope#1223] opened 2024-04-03 18:39 UTC
SteamOS version: 3.5.17
Opted into Steam client beta?: Not currently, but have tried it for testing purposes
Opted into SteamOS beta?: Not currently, but have tried it for testing purposes
Have you checked for updates in Settings > System?: Yes
Please describe your issue in as much detail as possible:

Video output to my AW3821DW monitor broke completely after the Steam Deck November 2023 update and hasn't worked since. I've tried 4 docks and multiple HDMI and DP cables (All of which work with the monitor with my MacBook Pro), active video converters to mask EDID, HDMI-CEC stripping adapters, HDMI scalers, deleting the modes.cfg file, updating the Deck to the preview firmware, and updating my monitor firmware, monitor safe mode, even getting a brand new OLED Deck to replace my LCD Deck, but nothing works. When booting while connected to the monitor, the Deck logo appears, but then disappears and the monitor gets no signal. When connected in Desktop Mode, the settings app seems to correctly detect the monitor and its properties, but nothing can make it display anything. I've filed a bug report with Valve and even contacted customer support, but nothing ever came of either. I'm fairly confident that this is a bug with SteamOS at this point, and others have reported this issue, too.

Here is the EDID file for the monitor which I managed to extract when in Desktop Mode:
[EDID](https://hastebin.com/share/gakeboneve.yaml)

Here are the outputs for both the /sys command and xrandr while the external monitor is connected: [Log File](https://hastebin.com/share/qawequheji.bash)

Steps for reproducing this issue:

1. Connect Steam Deck to Alienware AW3821DW monitor with any USB-C dock and video cable
2. See that video out only appears during the boot logo, and has no signal otherwise
3. Extract EDID and see it has a conformity failure

**Comment by kisak-valve** [comment] 2024-04-03 18:47
Hello @ameturpoet, there's no value in fragmenting the discussion of your issue across multiple issue trackers. Closing as a duplicate of https://github.com/ValveSoftware/SteamOS/issues/1466.

**Closed by kisak-valve** 2024-04-03 18:47 UTC
