### ISSUE TITLE
Regression from 3.12.5: Segmentation fault with nvidia, wlroots and gamescope 3.12.7

### ISSUE THREAD

**Issue by hashworks** [ValveSoftware/gamescope#983] opened 2023-10-11 19:44 UTC
Updating gamescope from 3.12.5 to 3.12.7 in Arch Linux breaks it on an nvidia system with wlroots / sway:
```
XWAYLAND_NO_GLAMOR=0 gamescope -W 2560 -H 1440 -f -- vkcube
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: physical device 10de:2484 compute queue doesn't support presenting on our surface, using graphics queue
vulkan: selecting physical device 'NVIDIA GeForce RTX 3070': queue family 0 (general queue family 0)
vulkan: physical device supports DRM format modifiers
zsh: segmentation fault (core dumped)  XWAYLAND_NO_GLAMOR=0 gamescope -W 2560 -H 1440 -f -- vkcube
```

Working 3.12.5 version:
```
XWAYLAND_NO_GLAMOR=0 gamescope -W 2560 -H 1440 -f -- vkcube
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: physical device 10de:2484 compute queue doesn't support presenting on our surface, using graphics queue
vulkan: selecting physical device 'NVIDIA GeForce RTX 3070': queue family 0
vulkan: physical device supports DRM format modifiers
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x48344241 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x48344258 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344241 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344258 (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [util/env.c:9] Loading WLR_NO_HARDWARE_CURSORS option: 1
wlserver: [types/output/output.c:382] WLR_NO_HARDWARE_CURSORS set, forcing software cursors
wlserver: [xwayland/server.c:108] Starting Xwayland on :1
wlserver: [types/wlr_compositor.c:673] New wlr_surface 0x564c389a0860 (res 0x564c38d30300)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 160
Selected GPU 0: NVIDIA GeForce RTX 3070, type: DiscreteGpu
wlserver: [types/wlr_compositor.c:673] New wlr_surface 0x564c38c6c460 (res 0x564c38d34d50)
xwm: got the same buffer committed twice, ignoring.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
```

Note: To make sway work on nvidia at all I'm setting some env variables, and I have to unset `XWAYLAND_NO_GLAMOR` with gamescope for performance reasons:
```sh
# https://github.com/crispyricepc/sway-nvidia/blob/main/wlroots-env-nvidia.sh
# Commit 409ea09

# Hardware cursors not yet working on wlroots
export WLR_NO_HARDWARE_CURSORS=1
# Set wlroots renderer to Vulkan to avoid flickering
export WLR_RENDERER=vulkan
# General wayland environment variables
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
# Firefox wayland environment variable
export MOZ_ENABLE_WAYLAND=1
export MOZ_USE_XINPUT2=1
# OpenGL Variables
export GBM_BACKEND=nvidia-drm
export __GL_GSYNC_ALLOWED=0
export __GL_VRR_ALLOWED=0
export __GLX_VENDOR_LIBRARY_NAME=nvidia
# Xwayland compatibility, explicitly disable it for xwayland games afterwards
export XWAYLAND_NO_GLAMOR=1
```

**Comment by hashworks** [comment] 2023-10-11 23:18
I bisected this, commit bd722f786f5a74f8282d903bd5eb3d331c4cd920 is at fault. In the log below `git bisect skip` didn't build (couldn't find `stb_image_resize.h`), `git bisect good` ran just fine and `git bisect bad` segfaulted.
```
 % git bisect start
status: waiting for both good and bad commits
 % git bisect good a8471d81b36ea1d9dc90a7d35f9ad0631feaf1ae
status: waiting for bad commit, 1 good commit known
 % git bisect bad d1eb70bb1a17072b48f7545af0fcf5f16d677aee
Bisecting: 35 revisions left to test after this (roughly 5 steps)
[a7dd157f519795e70cd14d5eaf27f66a09a2d47a] Consume KeyDown event if key will be consumed as a shortcut when the user releases the key
% git bisect skip
Bisecting: 35 revisions left to test after this (roughly 5 steps)
[8f5a251638fab80717a28a997b5892d2c1250035] layer: Cleanup fallback surface in DestroySurfaceKHR
% git bisect skip
Bisecting: 35 revisions left to test after this (roughly 5 steps)
[63fb573900f7be5f946c6fe3df42c1256e08cf58] build: Add reshade submodule
% git bisect good 63fb573900f7be5f946c6fe3df42c1256e08cf58
Bisecting: 34 revisions left to test after this (roughly 5 steps)
[1297270c9194b48d809bff8b649d732f57121b41] layer: Fix check for offsetted toplevel windows
% git bisect skip
Bisecting: 34 revisions left to test after this (roughly 5 steps)
[2aa742b0805114a5999dc571f227098ffd392f43] reshade: Fix GAMESCOPE_SDR_ON_HDR_NITS define
% git bisect skip
Bisecting: 34 revisions left to test after this (roughly 5 steps)
[4f4ace5ee050c6600aab5459c0a8b89a085f9237] rendervulkan: Expose some additional internal formats in the format table
% git bisect bad 4f4ace5ee050c6600aab5459c0a8b89a085f9237
Bisecting: 1 revision left to test after this (roughly 1 step)
[bd722f786f5a74f8282d903bd5eb3d331c4cd920] rendervulkan: Get a general graphics+compute queue as well as a async compute queue
% git bisect bad bd722f786f5a74f8282d903bd5eb3d331c4cd920
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[191a85da047f7754fc26881f7944fc4d51eeb98b] rendervulkan: Move CVulkanDevice to header
% git bisect good 191a85da047f7754fc26881f7944fc4d51eeb98b
bd722f786f5a74f8282d903bd5eb3d331c4cd920 is the first bad commit
commit bd722f786f5a74f8282d903bd5eb3d331c4cd920
Author: Joshua Ashton <joshua@froggi.es>
Date:   Fri Sep 8 04:09:22 2023 +0100

    rendervulkan: Get a general graphics+compute queue as well as a async compute queue

 src/rendervulkan.cpp | 55 +++++++++++++++++++++++++++++++++++++++++-----------
 src/rendervulkan.hpp |  6 ++++++
 2 files changed, 50 insertions(+), 11 deletions(-)
```

**Comment by Joshua-Ashton** [comment] 2023-10-12 09:20
I appreciate you doing the bisect, but this is a dupe of https://github.com/ValveSoftware/gamescope/issues/948 =(

**Comment by kisak-valve** [comment] 2023-10-12 12:24
Closing in favor of the older issue report.

**Closed by kisak-valve** 2023-10-12 12:24 UTC
