### ISSUE TITLE
S.T.A.L.K.E.R. 2 GPU droping frequency after hour of playing

### ISSUE THREAD

**Issue by Isemenuk27** [ValveSoftware/gamescope#1686] opened 2024-12-26 07:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

After playing for one hour or so, game starts to stutter. Restarting game returns it back to normal.
Here's video: [https://youtu.be/ucavBH4gWYI?si=LSpjXiMLI3T9cMkw](url)
It looks like stutters caused by changes in GPU frequency from ~2200 to ~1400.

### Steps To Reproduce

1. Launch S.T.A.L.K.E.R. 2 with `gamescope --force-grab-cursor -f -w 1920 -h 1080 -r 75 --hdr-enabled --hdr-debug-force-output --xwayland-count 2 -- env STEAM_MULTIPLE_XWAYLANDS=1 DXVK_HDR=1 ENABLE_HDR_WSI=1 PROTON_LOG=1  %command%` startup parameters.
2. Play for nearly one hour

### Hardware information

```markdown
- Distro: Manjaro Linux Kernel: 6.12.4-1
- CPU: 8-core AMD Ryzen 9 7950X3D
- GPU: AMD Radeon RX 7900 GRE
- Driver Version: Mesa 24.2.8-arch1.1
```

### Software information

```markdown
- Desktop environment: Plasma 6.2.4
- Session type: wayland
- Gamescope version: 3.16.1-1-g1c9495c (gcc 14.2.1)
- Gamescope launch command(s): gamescope --force-grab-cursor -f -w 1920 -h 1080 -r 75 --hdr-enabled --hdr-debug-force-output --xwayland-count 2 -- env STEAM_MULTIPLE_XWAYLANDS=1 DXVK_HDR=1 ENABLE_HDR_WSI=1 PROTON_LOG=1  %command%
```

### Which gamescope backends have the issue you are reporting?

- [X] Wayland (default for nested gamescope)
- [ ] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

### Logging, screenshots, or anything else

Compressed proton log output [(1)steam-1643320.zip](https://github.com/user-attachments/files/18250504/1.steam-1643320.zip)

**Comment by matte-schwartz** [comment] 2024-12-26 07:20
Have you tried the LD_PRELOAD workaround from https://github.com/ValveSoftware/steam-for-linux/issues/11446 / https://github.com/ValveSoftware/gamescope/issues/697#issuecomment-2136661525

**Comment by Isemenuk27** [comment] 2024-12-27 08:34
Yes, it worked 4~5 hours - no issues. Can you please explain what this parameter does and why its needed?

**Comment by matte-schwartz** [comment] 2024-12-27 15:40
This is a duplicate of #697 then. 

`LD_PRELOAD=` clears out any libraries that get preloaded before the game runs, like the Steam Overlay.

**Comment by kisak-valve** [comment] 2024-12-27 15:45
Closing as a duplicate.

**Closed** 2024-12-27 15:45 UTC
