### ISSUE TITLE
Gamescope freezing lethal company after a few seconds.

### ISSUE THREAD

**Issue by ZiadIDev** [ValveSoftware/gamescope#1646] opened 2024-11-30 18:01 UTC
Os: Arch linux

Kernal: 6.12.1

De: Kde plasma 6.2.4

Cpu: 15-4590

Gpu: Gtx 1050-ti

Driver: Nvidia proprietary 565.57.01-2

Gamescope: 3.15.14-1

When ever i run lethal company with gamescope the game works fine but after a few seconds the game start freezing and there's no audio, But when i run it without gamescope the game works perfectly well, But in any other game works fine with gamescope enabled.

This is the argument that i used:

gamescope -W 1920 -H 540 -- %command%

**Comment by matte-schwartz** [comment] 2024-12-01 00:47
I haven't been able to reproduce this yet on a 4090 with the same driver version, kernel version, plasma desktop version, and gamescope version. Are you using Plasma X11 or Wayland?

**Comment by sharkautarch** [comment] 2024-12-03 15:46
It could be that this issue is specific to only certain nvidia gpus

@ZiadIDev 
Do any of the following also freeze when run from a terminal emulator (outside of steam):
`gamescope -- glxgears`
`gamescope -- vkcubes`
If the glxgears cmd works fine, but vkcube freezes, try running w/ the env var `ENABLE_GAMESCOPE_WSI=0`
If both cmds work fine, then try changing the steam launch option to: `LD_PRELOAD="" gamescope -W 1920 -H 540 -- %command%`
If gamescope freezes for both cmds, and you’re using wayland kde/plasma, try adding this gamescope param `--backend sdl`

**Comment by ZiadIDev** [comment] 2024-12-03 16:27
> I haven't been able to reproduce this yet on a 4090 with the same driver version, kernel version, plasma desktop version, and gamescope version. Are you using Plasma X11 or Wayland? 

I'm sorry i didn't see the comment, Can you explain what the difference between them ?

**Comment by sharkautarch** [comment] 2024-12-03 16:53
> > I haven't been able to reproduce this yet on a 4090 with the same driver version, kernel version, plasma desktop version, and gamescope version. Are you using Plasma X11 or Wayland?
> 
> I'm sorry i didn't see the comment, Can you explain what the difference between them ?

I don’t have any experience with recent versions of kde, but Looking at the archwiki, I believe that the setting for whether plasma/Kwin use Wayland or x11 is based on the display manager setting (which is apparently usually sddm for plasma) 
I think that you’re probably currently using wayland if you didn’t change the configuration yourself, unless you happen to have a really old configuration (tho that’d be unlikely, since iirc pacman updates would of automatically updated the config w/ each package update if you never touched the config files yourself)
See:
https://wiki.archlinux.org/title/SDDM#KDE_Plasma_/_KWin

**Comment by ZiadIDev** [comment] 2024-12-03 20:21
> It could be that this issue is specific to only certain nvidia gpus
> 
> @ZiadIDev 
> Do any of the following also freeze when run from a terminal emulator (outside of steam):
> `gamescope -- glxgears`
> `gamescope -- vkcubes`
> If the glxgears cmd works fine, but vkcube freezes, try running w/ the env var `ENABLE_GAMESCOPE_WSI=0`
> If both cmds work fine, then try changing the steam launch option to: `LD_PRELOAD="" gamescope -W 1920 -H 540 -- %command%`
> If gamescope freezes for both cmds, and you’re using wayland kde/plasma, try adding this gamescope param `--backend sdl`

I tried all of them and still gamescope freezing the game.

**Comment by ZiadIDev** [comment] 2024-12-04 01:04
I managed to solve the problem by adding PROTON_LOG=1 to see the log and got these 2 errors
```
 02:27:35.035] [MANGOHUD] [error] [nvctrl.cpp:56] XNVCtrl didn't find the correct display
[2024-12-04 02:27:35.035] [MANGOHUD] [error] [battery.cpp:29] No battery found
```
So i turned off mangohud by adding MANGOHUD=0 and it works now.

**Comment by kisak-valve** [comment] 2024-12-04 01:42
Most likely https://github.com/flightlessmango/MangoHud/issues/1314.

Closing as not a gamescope bug.

**Closed by kisak-valve** 2024-12-04 01:42 UTC
