### ISSUE TITLE
gamescope cursor in not render correctly

### ISSUE THREAD

**Issue by l12436** [ValveSoftware/gamescope#1099] opened 2024-01-14 14:36 UTC
If you run "gamescope chromium-browser" and let cursor change to other type like click URL
the cursor is not render correctly 

![image](https://github.com/ValveSoftware/gamescope/assets/2596649/23331130-b567-4b31-ac2e-1b3a5fabaaa1)

**Comment by NolanSyKinsley** [comment] 2024-01-25 16:24
I have the same issue in many games. Anything with animated cursors and half the cursor is missing, but they don't always need to be animated to cause the issue. Sims 3 is a game that reliably reproduces it for me, Titan Quest Anniversary Edition also has the issue but it is less noticeable as their cursors seem to be offset so only have a small part cut off.

**Comment by AlexFolland** [comment] 2024-02-14 04:37
Magic The Gathering Arena is another game which exhibits this behavior.  It is a free-to-play game, so it may serve as a useful test case.

**Comment by Neurognostic** [comment] 2024-05-04 17:43
OS: Arch Linux
Display Server: X11
Desktop: BSPWM
GPU Driver: nvidia 550.78
Gamescope: 3.14.12.r0.gfb5e86b-1 (latest master branch commit)
Mode: nested

I have this issue in every application with a cursor. Applications with the cursor as a primary interaction method are not pleasant to use—and borderline unusable—through gamescope with up to half the cursor glyphs missing.

A couple examples:

Helldivers 2
![gamescope-helldivers2-cursor](https://github.com/ValveSoftware/gamescope/assets/23530447/351c1898-bc8a-43c9-9604-9b49a035d684)
![gamescope-helldivers2-cursor2](https://github.com/ValveSoftware/gamescope/assets/23530447/53770ae1-7ec9-4252-b546-9fbc0fe91836)


Guildwars 2
![gamescope-guildwars2-cursor1](https://github.com/ValveSoftware/gamescope/assets/23530447/3bf0587c-5b7b-483f-b51c-55d195b1374f)
![gamescope-guildwars2-cursor2](https://github.com/ValveSoftware/gamescope/assets/23530447/a6e4dbfc-a3a0-4486-a6c3-824103c5596a)

**Comment by nodgear** [comment] 2024-05-12 11:09
OS: Fedora 41
Display Server: X11
Desktop: Gnome
GPU Driver: nvidia 550.78
Gamescope: 3.14.12
Mode: Fullscreen

Same issue over here

**Comment by Joshua-Ashton** [comment] 2024-05-12 20:27
This only affects NVIDIA proprietary and not AMD or NVK. I don't see anything obvious, so probably some driver bug there?

**Comment by AlexFolland** [comment] 2024-05-12 21:54
This only affects gamescope and not when running the same games outside gamescope.  What's the difference in how the cursor image is displayed in those cases?  Discovering that may lead to a solution.

**Comment by Joshua-Ashton** [comment] 2024-05-12 22:49
It's just a small linear image sampled normally.

**Comment by AlexFolland** [comment] 2024-05-13 02:58
@esullivan-nvidia Is this something Nvidia can look into in the proprietary driver?  It sounds like the fix may be relatively simple if identified.  Also, sorry if pinging you is incorrect.  You were the first Nvidia employee I could find with contributions here.

**Comment by brain-anti-freeze** [comment] 2024-05-13 06:54
I think its related to [this](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4596?commit_id=928f2259921e71489df62b0ae8ed778626b76f42) (also addressed [here](https://invent.kde.org/plasma/kwin/-/merge_requests/4695/diffs)) - the Nvidia driver can't render to linear, so I guess this is causing the cursor image to get corrupted.  Maybe `vulkan_create_texture_from_bits()` could detect that and convert it on the CPU instead ?

I've also noticed that the cursor always causes composition (never uses the hardware plane), could be related.

**Comment by Joshua-Ashton** [comment] 2024-05-13 08:34
We don't render to linear, we upload as-linear.

> I've also noticed that the cursor always causes composition (never uses the hardware plane), could be related.

We never use the cursor plane

**Comment by esullivan-nvidia** [comment] 2024-05-13 16:21
> @esullivan-nvidia Is this something Nvidia can look into in the proprietary driver? It sounds like the fix may be relatively simple if identified. Also, sorry if pinging you is incorrect. You were the first Nvidia employee I could find with contributions here.

Yes, I have created NVIDIA bug 4646690 for investigating this issue. Thank you for the ping. I will provide an update here when I have more information.

**Comment by Rodancoci** [comment] 2024-06-30 21:30
> @esullivan-nvidia Is this something Nvidia can look into in the proprietary driver? It sounds like the fix may be relatively simple if identified. Also, sorry if pinging you is incorrect. You were the first Nvidia employee I could find with contributions here.
> 
> Yes, I have created NVIDIA bug 4646690 for investigating this issue. Thank you for the ping. I will provide an update here when I have more information.

Hi! Do you have any update on this bug report? Could you link it to follow its progress please?

**Comment by esullivan-nvidia** [comment] 2024-07-16 22:03
Sorry for the delay. We have root caused the issue in the driver and are still working on a fix. I will let you know when a driver is available for you to test.

**Comment by Martmists-GH** [comment] 2024-09-01 11:55
> This only affects NVIDIA proprietary and not AMD or NVK. I don't see anything obvious, so probably some driver bug there?

nvidia-open is also affected from my testing.

**Comment by MisterrrX** [comment] 2024-09-03 15:09
> Sorry for the delay. We have root caused the issue in the driver and are still working on a fix. I will let you know when a driver is available for you to test.

Any update on this? Still got the issue on driver 560.35.03 in Dota

**Comment by AlexFolland** [comment] 2024-09-03 15:13
I have an additional data point about this issue, in case it matters.  I have a new AMD GPU in my exact same PC with the same OS setup (so, specifically not a separate device like a Steam Deck, but just a change of GPU from Nvidia GTX 1080 Ti to AMD Radeon 7900 XT), and have confirmed that the issue is not reproducible with that AMD GPU.

**Comment by z3r0d0n3** [comment] 2024-10-16 13:37
still affected with nvidia-open-dkms Driver Version: 560.35.03

**Comment by Fxzzi** [comment] 2024-10-20 11:21
Hi @esullivan-nvidia how is the fix going? Will it be provided in the next series of driver updates? (565 i assume)

**Comment by esullivan-nvidia** [comment] 2024-10-22 05:45
> Hi @esullivan-nvidia how is the fix going? Will it be provided in the next series of driver updates? (565 i assume)

Yes, 565 will contain a fix for this issue.

**Comment by notpentadactyl** [comment] 2024-10-22 13:30
https://www.nvidia.com/en-us/drivers/details/233008/

> Fixed a bug that caused the cursor image to be truncated on Gamescope: https://github.com/ValveSoftware/gamescope/issues/1099

**Closed** 2024-10-22 14:10 UTC

**Comment by sfjuocekr** [comment] 2024-10-31 19:24
I had a similar case of the half cursor being rendered when I used gamescope and solved it by setting:

~/.Xdefaults:
```
Xcursor.size: 24
```
