### ISSUE TITLE
Strange Frametime Problem and Hacky way of getting some games to run with a proper frametime.

### ISSUE THREAD

**Issue by massatt212** [ValveSoftware/gamescope#873] opened 2023-05-09 20:25 UTC
My 32" TV has a resolution of 1366x768 59.94hz
So games like street fighter 5, mostly unreal engine 4 games games me frame time issues, my way of getting a smoother frame time, is to use a resolution that supports 60hz like 1080p or 720p and i have to set gamescope to use "-r 59" in order to fix the stuttering.

idk if you guys can add support for monitors hz with decimals i think it will fix a lot of stuttering in some games or many games
PC specs

RX 6400 LP
Intel Xeon E-1240 V3
8gb or 16gb ram according to which pc im on

if you guys can look in to it, it may be a big help for fighting games, for any more information just ask.

**Comment by Plagman** [comment] 2023-06-06 00:27
I think this sounds like a dupe of https://github.com/ValveSoftware/gamescope/issues/847

**Closed by Plagman** 2023-06-06 00:27 UTC
