### ISSUE TITLE
Gamescope blocks the Steam frame rate counter.

### ISSUE THREAD

**Issue by Gibitwit** [ValveSoftware/gamescope#1477] opened 2024-08-20 01:10 UTC
When running a game with Steam and Gamescope, while Steam's frame rate counter is enabled, the counter will not appear.  I think this problem is related to the screenshot issue.  https://github.com/ValveSoftware/gamescope/issues/1476

Gamescope version:  3.14.24-11

**Comment by kisak-valve** [comment] 2024-08-20 01:37
Hello @Gibitwit, the same as #1476. Closing as a duplicate of #835.

**Closed by kisak-valve** 2024-08-20 01:37 UTC
