### ISSUE TITLE
Gamescope fails when set to 5120x1440 with latest changes

### ISSUE THREAD

**Issue by ninjaquick** [ValveSoftware/gamescope#1171] opened 2024-03-03 04:58 UTC
Version: commit@58aa2ec
Distribution: Arch
DE: Plasma 6.0.0 (Wayland)
```
GPU0:
        apiVersion         = 1.3.278
        driverVersion      = 24.0.99
        vendorID           = 0x1002
        deviceID           = 0x73bf
        deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName         = AMD Radeon RX 6900 XT (RADV NAVI21)
        driverID           = DRIVER_ID_MESA_RADV
        driverName         = radv
        driverInfo         = Mesa 24.1.0-devel (git-529efb1f9b)
        conformanceVersion = 1.3.0.0
```

Applications launched with `./gamescope -w 5120 -h 1440 -W 5120 -H 1440 -f -- ` fail to `gamescope: ../src/edid.cpp:53: void gamescope::set_bit_range(uint8_t*, size_t, size_t, uint8_t): Assertion '(bits & ~bitmask) == 0' failed.`

Output for 5120x1440
```log
./gamescope -w 5120 -h 1440 -W 5120 -H 1440 -f -- vkgears
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
xdg_backend: Seat name: 
xdg_backend: PreferredMetadata: Red: 0.708 0.292, Green: 0.17 0.797, Blue: 0.131 0.046, White: 0.3127 0.329, Max Luminance: 1015 nits, Min Luminance: 0.0506 nits, Max Full Frame Luminance: 604 nits
xdg_backend: PreferredMetadata: Red: 0.708 0.292, Green: 0.17 0.797, Blue: 0.131 0.046, White: 0.3127 0.329, Max Luminance: 1015 nits, Min Luminance: 0.0506 nits, Max Full Frame Luminance: 604 nits
...
vulkan: selecting physical device 'AMD Radeon RX 6900 XT (RADV NAVI21)': queue family 1 (general queue family 0)
vulkan: physical device supports DRM format modifiers
wlserver: [backend/headless/backend.c:67] Creating headless backend
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   NV12 (0x3231564E)
vulkan:   AB4H (0x48344241)
vulkan:   XB4H (0x48344258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:17] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:108] Starting Xwayland on :2
The XKEYBOARD keymap compiler (xkbcomp) reports:
...
Errors from xkbcomp are not fatal to the X server
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x5a207aca0440 (res 0x5a207abe2b10)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 91
vblank: Using timerfd.
gamescope: ../src/edid.cpp:53: void gamescope::set_bit_range(uint8_t*, size_t, size_t, uint8_t): Assertion `(bits & ~bitmask) == 0' failed.
(EE) failed to read Wayland events: Broken pipe
Aborted
```

No error occurs when the resolution is set to 2560 1440, etc.

Output at 2560x1440 (Success)

```log
./gamescope -w 2560 -h 1440 -W 2560 -H 1440 -f -- vkgears
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
xdg_backend: Seat name: 
xdg_backend: PreferredMetadata: Red: 0.708 0.292, Green: 0.17 0.797, Blue: 0.131 0.046, White: 0.3127 0.329, Max Luminance: 1015 nits, Min Luminance: 0.0506 nits, Max Full Frame Luminance: 604 nits
xdg_backend: PreferredMetadata: Red: 0.708 0.292, Green: 0.17 0.797, Blue: 0.131 0.046, White: 0.3127 0.329, Max Luminance: 1015 nits, Min Luminance: 0.0506 nits, Max Full Frame Luminance: 604 nits
...
vulkan: selecting physical device 'AMD Radeon RX 6900 XT (RADV NAVI21)': queue family 1 (general queue family 0)
vulkan: physical device supports DRM format modifiers
wlserver: [backend/headless/backend.c:67] Creating headless backend
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   NV12 (0x3231564E)
vulkan:   AB4H (0x48344241)
vulkan:   XB4H (0x48344258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:17] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:108] Starting Xwayland on :2
The XKEYBOARD keymap compiler (xkbcomp) reports:
...
Errors from xkbcomp are not fatal to the X server
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x61f2cde1c430 (res 0x61f2cde1bd20)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 91
vblank: Using timerfd.
josh edid: Patching res 800x1280 -> 2560x1440
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x61f2ce0f8fc0 (res 0x61f2cde44d40)
...
The XKEYBOARD keymap compiler (xkbcomp) reports:
...
Errors from xkbcomp are not fatal to the X server
[Gamescope WSI] Creating Gamescope surface: xid: 0x400000
[Gamescope WSI] Atom of T was wrong type. Expected XCB_ATOM_CARDINAL.
[Gamescope WSI] Atom of T was wrong type. Expected XCB_ATOM_CARDINAL.
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x61f2ce0fd930 (res 0x61f2cded8220)
[Gamescope WSI] Made gamescope surface for xid: 0x400000
[Gamescope WSI] Surface state:
  steam app id:                  0
  window xid:                    0x400000
  wayland surface res id:        6
  layer client flags:            0x0
  server hdr output enabled:     false
  hdr formats exposed to client: false
[Gamescope WSI] Creating swapchain for xid: 0x400000 - minImageCount: 3 - format: VK_FORMAT_B8G8R8A8_SRGB - colorspace: VK_COLOR_SPACE_SRGB_NONLINEAR_KHR - flip: true
[Gamescope WSI] Created swapchain for xid: 0x400000 - imageCount: 3
xdg_backend: PreferredMetadata: Red: 0.708 0.292, Green: 0.17 0.797, Blue: 0.131 0.046, White: 0.3127 0.329, Max Luminance: 1015 nits, Min Luminance: 0.0506 nits, Max Full Frame Luminance: 604 nits
xdg_backend: PreferredMetadata: Red: 0.708 0.292, Green: 0.17 0.797, Blue: 0.131 0.046, White: 0.3127 0.329, Max Luminance: 1015 nits, Min Luminance: 0.0506 nits, Max Full Frame Luminance: 604 nits
[Gamescope WSI] Swapchain recieved new refresh cycle: 16.67ms
xdg_backend: Changed refresh to: 120
[Gamescope WSI] Swapchain recieved new refresh cycle: 8.33ms
```

**Comment by ninjaquick** [comment] 2024-03-03 05:07
A little more info:

 -w 3840 -h 1080 -W 5120 -H 1440 works, so it seems to have a problem when the nested resolution is big.

**Comment by sharkautarch** [comment] 2024-03-03 16:23
@ninjaquick 
hmmm
try building and running gamescope [built w/ clang UBsan](https://gist.github.com/sharkautarch/ff5dc08e8fba3f5a337bae9386c68703)

I know that clang UBsan will report some false positives, 
but if you compare the output between 5120x1440 and 3840x1080 maybe there will be a true positive

**Comment by Joshua-Ashton** [comment] 2024-03-03 16:58
the issue is an assert in set_bit_whatever in edid.cpp, im not sure what the problem is, probably an OBOE on the range or something.

**Comment by sharkautarch** [comment] 2024-03-03 18:14
> the issue is an assert in set_bit_whatever in edid.cpp, im not sure what the problem is, probably an OBOE on the range or something.


IDK, I couldn't find any out of bound access of array/vector, tho could still be an undetected range issue
Interestingly enough, it seems like any height at or above 4096 -- **!!!! power of two !!!! ** triggers the assert fail:
https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBJmGqQADqgKhE4MHt6%2BekkpjgJBIeEsUTFccbaY9nkMQgRMxAQZPn5cFVVptfUEBWGR0XoKdQ1NWa2DXT1FJRIAlLaoXsTI7BzmAMzByN5YANQma24AbpgOJPvYJhoAguub25h7B8iD%2BILnlzdmGwxbXrv7blECiUDXe11uP3ujzcL1oeAiADoEGDPt9fv8Di8nEiUQB6XE7AAqAE8Eg9iQtiDs0LsENFMKQdiQdrRUEx0DtDDtMKpWAl6AiPjtxo5kNSBIMeQkqV5ggQ1mYAPoEHbYAAiAEk1YqALJXAAaiosAQA8m4ANKKtwmuShQmPNU7MwAVgAbPsrNcdt7hXVReKGJLVNKdrLBArlarNdrjWbLUINQAtbAOnZlAAcHqFPpFeDFaEDBClMrlEZV6q1uoNiqEhKuoTVVwAStrCRqdRrQgBxK02u2pzNrT1XH2%2Bpj%2BgtBkNh%2BVK8vRo0ATUJ2EVauwQjcTY1ykJJqbvdt9v2jskWa9Ob9eYDU5L4bnUcrFmXq/Xm%2B3u/3NaTKZPacHw6jrm%2BYSkWwZ3rOkYVtqeqGm%2BW47nuB61vWjYtoqbYdt2h79n%2B7pDtm3rATeYHTqWD7QVWcEbghn4HtapoHsoJqdoSOHHmsjpmOeI6XuO16TqREFlo%2BMHVvBH5IYqG51saGpCAAEuqGHtp2PYahp7GppIZ4EReRFXiBhbFqG5FQQusFrjRklfm4ABqbGYWpvZvlpf66cOxHBHCISmYI6aRsAmAEIqESEIqxCGEFEAzgFKqHGIjIpAAXpgkYIHgwAIEleCpZGrIAO4zIRewAOyAaOOa5WlKoMDxlU%2BrFkZhQQLBMAoADWPElaO7UggQEAZVl0J/qVexmO6E07ENCCPBcnEsqgRXdfplUMKmM07AAtItBXjRYab1Q1OwtW1nWpjFcpxTMOxQFwI0HDsDA3TtXDFXpvENcQwWLOtl3%2BcqN0QAltBzecu03eYronYQZ1dR9o4mKVaofCVXkMD5DyHKgeAckoIUtRFUWYP9BBxTsABUIM5XlKozTTNW7YyTUqi1CjFatSMVQ1KWM3VCPHSzMOte18PDj1Pp9dEA2bQCo3jZN0Oy2s82OoV73i6to7rX%2Bm07YV%2B2HQLDWnaLF0s0DED3XLj3PdtaYaxL3pUNKcpUBALzRGQ5hmDNJ7mM6yVeIyhX%2By6QeMmzYfOggwdPdHEfC3D0exyYzpuHVZhmIy9NM8LCiMgwkew6Ljtaz6LvEG7HsEFgxDe1nUecQHseMgAfqbnUp3HUcTR3Jdd83Lqp%2BnmfZ/njIQP3IudXM%2BcKzs09w2Xn2VVLDRQGzC9L6XDp/hoK9O5TIMK3%2BbcQJ3HUPW4ENHQ1VNiGVbh/qT10X4QCjX7fxtlSj4L/6vdGmMdjY1xjsBI45kAIEVJgfA6BFRQJOB1BQPhX7KgpidVkyAOoc1XlzI%2BQsUEsFTBoO%2BlV%2BBUlJiJPAJCPQ7BoQCUSRpTQWm/Mme2XA6F4GsNYXBx1KpEP2n%2BCIWCurOgsNw50KMPoEKupGRB2DBF/hnGWCALpXQvT8pBAaRDD7l29CI1A2C04WDKKVNOjo/wKOQT4MhSM/5XGIoJEyhDFRdlYJgBQaAyQWHajgOBJiLF705uVI%2BGhVAaHiDscJVAqCMhiXE6JqhYnxOSYkhJqSUlJMiakrgTBUmSFKqk10ABOYpZSwmqDWOmTJ0hsmtGyVEjJSTyj1NSRoOp4SmDOnafkpJXAmmqFKjUypXAilJLWMgVJpUGldIZEk50syqlTKSREMpLS1jtJWeE50gznSdIifESpOTGntKWRoc5lyznXLabc8JFzrnHKuXciJzz7nnJqRMg5rTwmSE%2BeEtY5yjn6JaXswZUh2n/NUCUpZkhBmugOUwQZJz7nIvBQyY5aL2mDKoNsw5BTxnhNdEs106Bik9KSaVTZSTXTUqJXEyppV4UUvuX08JPzVAco5Si/FpyklUDJXy9lZLKnOjZUM100zCURPmai3pqSuWDMVQqpVwLV6jjlUK3l4SBnYr1VqnlhqsWnMxfqzV5rtWWoedkqFGhx73LpVatV/DwmYEldk917yblEvFa6cVGhHVGrNU60gpqDXGotUG8Nwag1hsjRGkN0ak3xtDSClNybE3pqzSGuNma81RuzQW/Fuai2loTWWmNzrjqFvLbWyt9aTVpvzXWjNFbo0lpbTWhtXaO3dubX2itvatVrHdCE6RmtAG1xACAY4pxiAAhZuDLsjBojjkwEIPALB%2BT%2BNxhALRIkvAAHVcYEGyvuh8XgFKYEyggFUfCfT4JBfiHYapUCeKeqgFUECCBQJ2N9Kg30FBnoYJ%2BjKRhprtWpPUWBnIIgLBVKevAn9iTBUFCCl407Z1EHnQcRdKtuRwL3QoNxHivGoB8X43AuMkokbYGRijSgqMcmsL6dA07eZEdo547xmBfGMbgTsG6ej1UV2ZFQh8DCFqkKHPQ6ETDnwrisu%2BRCtk%2ByEi4Twyw96GqPpEw1IWFMIjEiLIqLAXjTPjiYKmKGsDcYmIBdDFjNCMGUQU6%2BayKnkI/gsWQ/heAqC3SMyZszyALN1Hs0EpGz9So3yC2lELYWmAmM4VI7T/Cyrc3S6OFRD5PDoAUiQXKF0goE3CpFIwJM4ume44lkxZ4pGMnGZISGBxGHpkhjFk6xn4s1fQJZkx3EpG%2Bay%2BeyMeW7LS29C/EroUyvEwvt16r5m%2BvhfEeYhrOwmstefo9drT8uvBd6/18RzofMyJBfwyu1dPb10ZD7YBJTTujx9ivEbAjgqzZCuV6KCsqsJZW0l8R9W1SNcZHUvdR6T2zXePh9MgmF4JME8NrLf2jurYsINyxC1IfoFPQjtJK09Ppau4Id2N2yDjTMA9kpacM4veR%2Bl/Gn2iYVb3VDVHy3jsWHWyDzbYPJ6hivTelUMOUxw8hlNRHr23s%2Bg56FgHJintY8dJe69WUReS4J%2Bdon/CcvpUK8lYrH3Cbfcq4t/7XPgeg52M1r%2Be2osHZ65z9HmOGe67MvFSbRvStffm3L2ra2LHW9tzbG%2B9vOv%2B4Vyds7mW3v4ls/A1kwAETBH4O7SnyhIFgeAH%2B99AcvCqHz9tcG%2BfC8ui8D7RkeWCtV2SlX2g6AJsNBzgbxkxwGhI5/m9iI30mBiyPojZGR97GoxBd%2BqBMC4EILpIo1BNmAniNIalwn/DvoEF%2BgRuzP8R8ANHHKHYbVggQDS7p/hy6QiRSLBurd9AmMQDhY9xk6ZInS%2BOuf1dV/N3brvw/91z%2BD52JD7XAcBzC0CcDOi8B%2BAcBaCkCoCcDPyWAsYKCUjLDjSAq8AECaAgFzAdQgBrBrAIj4FEHEEkGSpgEcCSCQFYGwGcC8AKAgDxCYHQEgGkBwCwBIBoBbp0DRDkCUCcEJDcExBbBRRcCug5I0C0BFjED0EXzUFhTMDEDEicA8CkDyH1DEgmgRDaAnBMEqGcFsCCAmgYxKHMGkBYARBeDABuBiC0D0HcC8BYBtRGDiCmH4DfQOB4DHB2EwE8gnBeBFjUFyiVDUFwg97qEeBYDUEEBVwsDKEsFUAGDAAKB2R4CYAFQmhkhQEqH8CCAiBiDsAQo5HyBKBqDUG6CtAGBGAoCaY2ChH0GQBzDkbVB2FbQvAnimCIGWBxDbRUAKCGCpCpQnhf5wjICEBbReCBiZQhDoBbRBFBTEBbTRETGiDVA9F9EMADGYAnhwYTHoCfxbS9H9GOCDGcRzHRBrFHHVQnjsjoCAb7GHEbHHGYBbTuGoDt7XG0CgwHHrGbEni7GYA0DTHejfGXEnFqjDF5hjEpDADTGzGCCYDzGLHEDLH8QCA9EgZbSoAsBjEAYeJbRJBBFUggmPFXGcQJFsgEBbT4CHC4zPFGZbSpTECoAXEklglYJiBbQ7EMB7E9FeBKBbQN4nifEchbQ54HEYlYk4mRRsD4k4zwlEkPG/GcT/GAkwZbQmgwFvFey0n1HH5tA6FpAuDckjAtCkCBDBC9DFD9CtA5CpACAmnZDJB2kMCTB9ClD6keECCdDDCeDNADCVAGlelDDdAWlTDWm2DBkOljDBmulWmlBzDIGLDLCzD6DgFUGmFwEcA7CqDpiuhbQIrUiVE56iEIgaClm3RUbYZoFvQYFYEzA4F4EEEkHNlEFkGcCUGkBQGam0G2AMGkBMFaBzBsGIAgDwYJD%2BG8EQD8GCGhAeKcA5l5kFnADIBihcAEFmC8C2bYa4x6BFF5HiCFGyCKAqDqCmHlGkAFSRQJBxGgFpmdnUGZkmj%2BHjkqioABYLn5mSCFlRRpiuilnlkQAeBcH0BUjrA1n9l1kNn4GEEtnNmpkUHpndkcB0F9kDnYHwUbn3kZk9loX1mkDt4pDOCSBAA%3D

**Comment by ninjaquick** [comment] 2024-03-13 07:21
I am getting around this issue by just removing the assert in set_bit_range. The edid block type being manipulated just doesn't allow the same space as the DisplayID Type I/VII which my display uses (and likely all others which are >4095 in either direction do as well).

Removing the assert as mentioned allows games to run, and it appears that HDR works as well. 

This is the relevant place in the logs:
```
josh edid: Patching res 800x1280 -> 1024x1440
pipewire: renegotiating stream params (size: 5120x1440)
```

I attached my edid as parsed by edid-decode.

[edid_out.txt](https://github.com/ValveSoftware/gamescope/files/14583851/edid_out.txt)

**Comment by sharkautarch** [comment] 2024-03-13 16:58
> I am getting around this issue by just removing the assert in set_bit_range. The edid block type being manipulated just doesn't allow the same space as the DisplayID Type I/VII which my display uses (and likely all others which are >4095 in either direction do as well).
> 
> Removing the assert as mentioned allows games to run, and it appears that HDR works as well.
> 
> This is the relevant place in the logs:
> 
> ```
> josh edid: Patching res 800x1280 -> 1024x1440
> pipewire: renegotiating stream params (size: 5120x1440)
> ```

That may behave ok in a lot of cases, but if an app relies on the resolution encoded in the patched edid, behavior might get wonky.
I think there is actually a way to directly encode 5k resolutions in an edid, since qemu also does edid patching, and was at some point updated to support 5k resolution edids.
However, I think it'd be simpler to try to use libdisplay-info functions to patch 5k resolutions...

**Comment by Zamundaaa** [comment] 2024-03-13 17:09
I think just not reporting the correct resolution would be okay, the real EDID of my monitor doesn't actually report the correct resolution in the "normal" EDID parts either, only in a DisplayID extension block:
```
Block 2, DisplayID Extension Block:
  Version: 1.2
  Extension Count: 0
  Display Product Type: Extension Section
  Video Timing Modes Type 1 - Detailed Timings Data Block:
    DTD:  5120x1440  119.970194 Hz   0:0    182.955 kHz    966.000000 MHz (aspect undefined, no 3D stereo, preferred)
               Hfront   48 Hsync  32 Hback   80 Hpol P
               Vfront    3 Vsync  10 Vback   72 Vpol N
    DTD:  5120x1440   99.996237 Hz   0:0    150.994 kHz    797.250000 MHz (aspect undefined, no 3D stereo)
               Hfront   48 Hsync  32 Hback   80 Hpol P
               Vfront    3 Vsync  10 Vback   57 Vpol N
    DTD:  5120x1440   59.976879 Hz   0:0     88.826 kHz    469.000000 MHz (aspect undefined, no 3D stereo)
               Hfront   48 Hsync  32 Hback   80 Hpol P
               Vfront    3 Vsync  10 Vback   28 Vpol N
  Checksum: 0xf3
```

> if an app relies on the resolution encoded in the patched edid, behavior might get wonky.

True, but that can be fixed later.

**Comment by sharkautarch** [comment] 2024-03-13 17:38
> I think just not reporting the correct resolution would be okay, the real EDID of my monitor doesn't actually report the correct resolution in the "normal" EDID parts either, only in a DisplayID extension block:
> 
> ```
> Block 2, DisplayID Extension Block:
>   Version: 1.2
>   Extension Count: 0
>   Display Product Type: Extension Section
>   Video Timing Modes Type 1 - Detailed Timings Data Block:
>     DTD:  5120x1440  119.970194 Hz   0:0    182.955 kHz    966.000000 MHz (aspect undefined, no 3D stereo, preferred)
>                Hfront   48 Hsync  32 Hback   80 Hpol P
>                Vfront    3 Vsync  10 Vback   72 Vpol N
>     DTD:  5120x1440   99.996237 Hz   0:0    150.994 kHz    797.250000 MHz (aspect undefined, no 3D stereo)
>                Hfront   48 Hsync  32 Hback   80 Hpol P
>                Vfront    3 Vsync  10 Vback   57 Vpol N
>     DTD:  5120x1440   59.976879 Hz   0:0     88.826 kHz    469.000000 MHz (aspect undefined, no 3D stereo)
>                Hfront   48 Hsync  32 Hback   80 Hpol P
>                Vfront    3 Vsync  10 Vback   28 Vpol N
>   Checksum: 0xf3
> ```
> 
> > if an app relies on the resolution encoded in the patched edid, behavior might get wonky.
> 
> True, but that can be fixed later.

huh, ok then...
I wonder if there'd be any point in (for any width/height above 4095) scaling the patched edid resolution down to fit within 4095x4095...
It would still look weird if an app relies on the patched edid's resolution, but maybe it'd look less weird, since the aspect ratio would be preserved

**Comment by Joshua-Ashton** [comment] 2024-03-14 04:41
The reason we do this and expose the actual EDID/resolution is that some games, eg. Returnal read the EDID for some (bad) reason, and in the instance of that game it breaks the Photo mode if the EDID resolution is wrong. :l

**Comment by Joshua-Ashton** [comment] 2024-03-14 04:46
I added some code to clamp it to 3840x3840 for now.

Perhaps someday we can add in a DisplayID block, if anything needs that.

**Comment by sharkautarch** [comment] 2024-03-14 14:50
@ninjaquick 
should be fixed in lastest gamescope git commit that Joshua Ashton made
use gamescope-git AUR package to get the latest fix from the gamescope git repo

**Comment by ninjaquick** [comment] 2024-03-22 05:13
Nice, yeah I'd done something similar but wasn't confident in changing aspect ratio

```cpp
diff --git a/src/edid.cpp b/src/edid.cpp
index 03e5de1..55460e4 100644
--- a/src/edid.cpp
+++ b/src/edid.cpp
@@ -323,8 +323,16 @@ namespace gamescope
     };
     std::vector<uint8_t> GenerateSimpleEdid( uint32_t uWidth, uint32_t uHeight )
     {
-        uWidth  = std::min<uint32_t>( uWidth,  3840 );
-        uHeight = std::min<uint32_t>( uHeight, 3840 );
+        const uint32_t maxResolution = 3840; 
+        if (uWidth > maxResolution)
+        {
+            // Pin uWidth to maxResolution and adjust uHeight accordingly
+            float modifier = maxResolution / static_cast<float>(uWidth);
+            uHeight = static_cast<uint32_t>( modifier * uHeight );
+            uWidth = maxResolution;
+        }
 
         // Does not patch refresh, nothing has cared about this yet.
         std::vector<uint8_t> edid( s_GamescopeBaseEdid, s_GamescopeBaseEdid + std::size( s_GamescopeBaseEdid ) );
```

**Closed** 2024-03-22 05:13 UTC
